export const seedData = {
  parentPools: [
    { id: "PP-01", species: "南美白对虾", count: 320, note: "春季亲本" },
  ],
  batches: [
    {
      id: "B-260601",
      species: "南美白对虾",
      parentPoolId: "PP-01",
      hatchDate: "2026-06-01",
      currentPool: "P-03",
      estimatedCount: 850000,
      status: "育苗中",
      cost: 12600,
    },
  ],
  ponds: [
    {
      id: "P-01",
      name: "育苗池1号",
      capacity: "40m³",
      purpose: "虾苗培育",
      status: "idle",
      disinfectionDate: "2026-05-28",
      note: "标准虾苗培育池，配备独立增氧系统",
    },
    {
      id: "P-02",
      name: "育苗池2号",
      capacity: "45m³",
      purpose: "虾苗培育",
      status: "idle",
      disinfectionDate: "2026-05-30",
      note: "",
    },
    {
      id: "P-03",
      name: "育苗池3号",
      capacity: "42m³",
      purpose: "虾苗培育",
      status: "active",
      disinfectionDate: "2026-05-25",
      note: "当前养殖南美白对虾 B-260601 批次",
    },
    {
      id: "P-04",
      name: "育苗池4号",
      capacity: "48m³",
      purpose: "暂养池",
      status: "cleaning",
      disinfectionDate: "2026-06-12",
      note: "消毒作业中，预计 6 月 14 日完成",
    },
    {
      id: "P-05",
      name: "育苗池5号",
      capacity: "48m³",
      purpose: "蟹苗培育",
      status: "idle",
      disinfectionDate: "2026-05-20",
      note: "计划用于三疣梭子蟹夏季苗种",
    },
    {
      id: "P-06",
      name: "育苗池6号",
      capacity: "36m³",
      purpose: "鱼种培育",
      status: "maintenance",
      disinfectionDate: "2026-05-15",
      note: "排水阀维修中，预计 6 月 16 日恢复",
    },
  ],
  records: [
    {
      id: "REC-1",
      batchId: "B-260601",
      date: "2026-06-12",
      poolId: "P-03",
      temperature: 28.2,
      salinity: 22,
      oxygen: 6.1,
      feed: 18,
      mortality: 0.8,
      abnormal: "无",
    },
  ],
  transfers: [
    {
      id: "TR-1",
      batchId: "B-260601",
      fromPool: "孵化桶",
      toPool: "P-03",
      date: "2026-06-03",
      count: 900000,
      reason: "初次入池",
    },
  ],
  sales: [],
  costItems: [
    {
      id: "COST-1",
      batchId: "B-260601",
      category: "饲料",
      date: "2026-06-05",
      amount: 2800,
      quantity: 350,
      unit: "kg",
      description: "丰年虫幼体饲料",
    },
    {
      id: "COST-2",
      batchId: "B-260601",
      category: "药品",
      date: "2026-06-08",
      amount: 1200,
      quantity: 5,
      unit: "L",
      description: "水质改良剂",
    },
    {
      id: "COST-3",
      batchId: "B-260601",
      category: "人工",
      date: "2026-06-10",
      amount: 3500,
      quantity: 7,
      unit: "工日",
      description: "育苗工人工资",
    },
    {
      id: "COST-4",
      batchId: "B-260601",
      category: "能源",
      date: "2026-06-12",
      amount: 1800,
      quantity: 600,
      unit: "kWh",
      description: "增氧和加温电费",
    },
    {
      id: "COST-5",
      batchId: "B-260601",
      category: "其他",
      date: "2026-06-13",
      amount: 500,
      quantity: 1,
      unit: "批",
      description: "消毒用品及耗材",
    },
  ],
  customers: [
    {
      id: "C-001",
      name: "青岛海润水产有限公司",
      contact: "张经理",
      phone: "13800138001",
      region: "山东青岛",
      note: "长期合作客户，主要采购南美白对虾苗",
    },
    {
      id: "C-002",
      name: "连云港兴渔养殖专业合作社",
      contact: "李社长",
      phone: "13900139002",
      region: "江苏连云港",
      note: "大型合作社，需求量稳定",
    },
    {
      id: "C-003",
      name: "温州东海苗种场",
      contact: "王场长",
      phone: "13700137003",
      region: "浙江温州",
      note: "蟹苗主要客户",
    },
  ],
  warnings: [],
  warningThresholds: {
    temperature: { yellowMin: 20, yellowMax: 32, redMin: 18, redMax: 35 },
    salinity: { yellowMin: 15, yellowMax: 30, redMin: 10, redMax: 35 },
    oxygen: { yellowMax: 4.5, redMax: 3 },
    mortality: { yellowMin: 2, redMin: 5 },
    abnormalKeywords: ["死苗", "变色", "发病", "浮头", "白斑", "红体", "溃烂", "停食", "狂游", "沉底"],
  },
  inventories: [],
};

export function getInitialSeed() {
  return JSON.parse(JSON.stringify(seedData));
}
